#!/usr/bin/env python3
"""Build and validate the output gallery and its health-backed navigation snapshot."""
from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

import yaml


BASE = Path(__file__).resolve().parents[1]
GALLERY = BASE / "05-outputs" / "index" / "output-gallery.md"
NAVIGATION = BASE / "05-outputs" / "index" / "index.md"
HEALTH = BASE / "06-runtime" / "state" / "current-health.json"
REQUIRED_FIELDS = {
    "output_id",
    "output_type",
    "used_units",
    "used_claims",
    "used_relations",
    "source_refs",
    "uncertain_points",
    "file_back_status",
}
LEGACY_CANDIDATE_FIELDS = (
    "new_candidate_units",
    "new_candidate_claims",
    "new_candidate_relations",
    "new_candidate_themes",
)
FILE_BACK_STATUSES = {
    "not_reviewed",
    "reviewed_no_candidates",
    "candidates_deferred",
    "candidates_ready",
    "applied",
    "rejected",
    "blocked",
    "filed_back",
}
EXCLUDED_OUTPUT_FILES = {
    "05-outputs/README.md",
    "05-outputs/process/README.md",
    "05-outputs/results/README.md",
    "05-outputs/output-registry.yml",
    "05-outputs/index/README.md",
    "05-outputs/index/output-gallery.md",
}


def load_records(base: Path = BASE) -> list[dict]:
    registry = base / "05-outputs" / "output-registry.yml"
    data = yaml.safe_load(registry.read_text(encoding="utf-8-sig")) or {}
    records = list(data.get("records", []))
    for path in sorted((base / "05-outputs").rglob("output-metadata.json")):
        record = json.loads(path.read_text(encoding="utf-8-sig"))
        record["_metadata_path"] = path.relative_to(base).as_posix()
        records.append(record)
    return records


def record_artifacts(record: dict, base: Path = BASE) -> list[str]:
    artifacts: set[str] = set()
    for pattern in record.get("artifact_patterns", []):
        artifacts.update(path.relative_to(base).as_posix() for path in base.glob(pattern) if path.is_file())
    metadata_path = record.get("_metadata_path")
    if metadata_path:
        parent = (base / metadata_path).parent
        for artifact in record.get("artifacts", []):
            path = parent / artifact
            if path.is_file():
                artifacts.add(path.relative_to(base).as_posix())
    return sorted(artifacts)


def candidate_count(record: dict) -> int:
    if "candidate_refs" in record:
        return len(record.get("candidate_refs") or [])
    return sum(len(record.get(field, [])) for field in LEGACY_CANDIDATE_FIELDS)


def render_gallery(records: list[dict], base: Path = BASE) -> str:
    status_counts = Counter(record.get("file_back_status", "missing") for record in records)
    lines = [
        "# Output Gallery and File-back Status",
        "",
        "> Generated by `python scripts/build_output_gallery.py`. Metadata sources are `05-outputs/output-registry.yml` and bundle-local `output-metadata.json` files.",
        "",
        "## Status summary",
        "",
        "| status | outputs |",
        "|---|---:|",
    ]
    for status in sorted(FILE_BACK_STATUSES):
        lines.append(f"| {status} | {status_counts.get(status, 0)} |")
    lines.extend([
        "",
        "## Outputs",
        "",
        "| output_id | type | artifacts | uncertain | candidates | file-back status |",
        "|---|---|---:|---:|---:|---|",
    ])
    for record in sorted(records, key=lambda item: item["output_id"]):
        lines.append(
            f"| `{record['output_id']}` | {record['output_type']} | {len(record_artifacts(record, base))} | "
            f"{len(record.get('uncertain_points', []))} | {candidate_count(record)} | {record['file_back_status']} |"
        )
    lines.extend([
        "",
        "## Boundaries",
        "",
        "- `reviewed_no_candidates` means semantic retrospective found no knowledge increment.",
        "- `candidates_deferred` means candidates exist but have not passed their typed gate.",
        "- `rejected` means no independently writeable fact exists or the output is only a derived display.",
        "- `filed_back` is accepted only as a historical compatibility value.",
        "- A candidate is not knowledge until evidence binding, semantic review, and typed apply are complete.",
        "",
    ])
    return "\n".join(lines)


def render_navigation_snapshot(text: str, health: dict) -> str:
    """Refresh only the generated metric rows while preserving navigation prose."""
    values = {
        "知识元总数": (health["summary"]["total_units"], "（以 `current-health.json` 当前快照为准）"),
        "claim 数": (health["claim_traceability"]["total_claims"], ""),
        "relation 数": (health["relation_health"]["relation_index_total"], ""),
        "structural_health": (f"{health['structural_health']['total']}/130", ""),
        "traceability": (f"{health['structural_health']['traceability']}/15", ""),
    }
    rendered = text
    for label, (value, suffix) in values.items():
        pattern = rf"(?m)^\|\s*{re.escape(label)}\s*\|.*?\|\s*([^|]+)\|$"
        match = re.search(pattern, rendered)
        if not match:
            raise ValueError(f"output navigation metric row missing: {label}")
        replacement = f"| {label} | **{value}**{suffix} | {match.group(1).strip()} |"
        rendered = re.sub(pattern, replacement, rendered, count=1)
    return rendered


def known_candidate_ids(base: Path) -> set[str]:
    path = base / "06-runtime" / "state" / "candidate-index.jsonl"
    if not path.is_file():
        return set()
    return {
        str(item["candidate_id"])
        for line in path.read_text(encoding="utf-8-sig").splitlines()
        if line.strip()
        for item in [json.loads(line)]
        if item.get("candidate_id")
    }


def validate_output_metadata(base: Path = BASE) -> list[dict]:
    findings: list[dict] = []
    records = load_records(base)
    candidate_ids = known_candidate_ids(base)
    output_ids = [record.get("output_id") for record in records]
    for output_id, count in Counter(output_ids).items():
        if not output_id or count > 1:
            findings.append({"issue": "output_id_missing_or_duplicate", "output_id": output_id, "count": count})

    covered: set[str] = set()
    for record in records:
        missing = sorted(REQUIRED_FIELDS - set(record))
        if missing:
            findings.append({"issue": "output_metadata_fields_missing", "output_id": record.get("output_id"), "missing": missing})
        status = record.get("file_back_status")
        if status not in FILE_BACK_STATUSES:
            findings.append({"issue": "output_file_back_status_invalid", "output_id": record.get("output_id"), "status": status})
        if "candidate_refs" not in record and not any(field in record for field in LEGACY_CANDIDATE_FIELDS):
            findings.append({"issue": "output_candidate_refs_missing", "output_id": record.get("output_id")})
        candidate_refs = record.get("candidate_refs", [])
        if not isinstance(candidate_refs, list):
            findings.append({"issue": "output_candidate_refs_invalid", "output_id": record.get("output_id")})
        else:
            for candidate_id in sorted(set(map(str, candidate_refs)) - candidate_ids):
                findings.append({
                    "issue": "output_candidate_ref_unknown",
                    "output_id": record.get("output_id"),
                    "candidate_id": candidate_id,
                })
        artifacts = record_artifacts(record, base)
        if not artifacts:
            findings.append({"issue": "output_artifact_pattern_empty", "output_id": record.get("output_id")})
        covered.update(artifacts)

    actual = {
        path.relative_to(base).as_posix()
        for path in (base / "05-outputs").rglob("*")
        if path.is_file()
        and path.relative_to(base).as_posix() not in EXCLUDED_OUTPUT_FILES
        and path.name != "output-metadata.json"
    }
    for path in sorted(actual - covered):
        findings.append({"issue": "output_artifact_unregistered", "path": path})
    gallery = base / "05-outputs" / "index" / "output-gallery.md"
    if not gallery.is_file() or gallery.read_text(encoding="utf-8") != render_gallery(records, base):
        findings.append({"issue": "output_gallery_stale", "file": "05-outputs/index/output-gallery.md"})
    return findings


def file_back_health(base: Path = BASE) -> dict:
    records = load_records(base)
    counts = Counter(record.get("file_back_status", "missing") for record in records)
    return {
        "total_outputs": len(records),
        "status_counts": dict(sorted(counts.items())),
        "deferred": counts.get("candidates_deferred", 0),
    }


def main() -> int:
    records = load_records()
    GALLERY.parent.mkdir(parents=True, exist_ok=True)
    GALLERY.write_text(render_gallery(records), encoding="utf-8")
    if not HEALTH.is_file() or not NAVIGATION.is_file():
        print("current-health.json or output navigation index is missing")
        return 1
    health = json.loads(HEALTH.read_text(encoding="utf-8"))
    navigation = render_navigation_snapshot(NAVIGATION.read_text(encoding="utf-8"), health)
    NAVIGATION.write_text(navigation, encoding="utf-8")
    findings = validate_output_metadata()
    if findings:
        for finding in findings:
            print(f"[{finding['issue']}] {finding.get('output_id') or finding.get('path') or finding.get('file')}")
        return 1
    print(f"written={GALLERY.relative_to(BASE).as_posix()} outputs={len(records)}")
    print(f"written={NAVIGATION.relative_to(BASE).as_posix()} health_snapshot=synchronized")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
